/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_JNICall */

#ifndef _Included_com_JNICall
#define _Included_com_JNICall
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_JNICall
 * Method:    helloC
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_JNICall_helloC
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
